### ISSUE TITLE
Change the blue

### ISSUE THREAD

**Issue by gerroon** [cwilliams5/Midnight-Trilium-Dark-Mode#2]
Hi

How can I change that blue bg color that is in the search window and the table edits?

The  blue is fine I just want it to be much darker.

thanks

**Comment by cwilliams5** [comment]
Hello, glad you like it. You can easy customize it by searching the note you put in Trilium to create it for the following: 
`0784b5`
That is the color code for the "highlight" blue I use. By replacing each instance of that with your desired color, your good to go.

You can use any color picker to adjust the color. Google [even has one built in](https://www.google.com/search?q=color+picker+0784b5). 

Let me know if this doesn't resolve your issue.
